blank_issues_enabled: true
contact_links:
  - name: "Tableau de suivi / Tracking board"
    url: https://github.com/orgs/performant-software/projects/41
    about: "Suivre l'avancement des tickets — Follow the progress of issues"
